version: '3.8'
services:
  app:
    container_name: hack-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8074:8074"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: kalinin_egor
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: sber
      # Redis inside the compose network uses default 6379
      REDIS_URL: redis://redis:6379
      REDIS_USER: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
      REDIS_DB: 0

  postgres:
    image: postgres:15
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: kalinin_egor
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: sber
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 5g
    cpus: 0.5

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6376:6379"  # Обычно Redis слушает на 6379
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
        reservations:
          memory: "128M"

volumes:
  postgres_data:
  redis_data:
